on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm test

      - run: npm run lint
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        project_id: mcp-server-everything
        workload_identity_provider: projects/625462337716/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: mcp-server-everything
        region: us-central1
        source: .
        env_vars: |-
          BASE_URI=https://example-server.modelcontextprotocol.io/sse
          NODE_ENV=production
          REDIS_TLS=0
        secrets: |-
          REDIS_URL=REDIS_URL:latest
        flags: |-
          --vpc-connector=redis-connector
          --service-account=cloudrun-service@mcp-server-everything.iam.gserviceaccount.com
          --allow-unauthenticated
