on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci
      - run: npm run build
      - run: npm test

      - run: npm run lint
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - uses: google-github-actions/auth@v2
      with:
        project_id: TODO
        workload_identity_provider: TODO

    - id: deploy
      uses: google-github-actions/deploy-cloudrun@v2
      with:
        service: mcp-server-everything
        region: us-central1
        source: .
        env_vars: |-
          BASE_URI=https://TODO
          REDIS_URL=redis://TODO
          REDIS_TLS=1
        secrets: |-
          REDIS_PASSWORD=REDIS_PASSWORD:latest
          REDIS_TLS_CA=REDIS_TLS_CA:latest
